<<<<<<< HEAD
# Generated by Django 5.1 on 2024-09-30 04:40
=======
# Generated by Django 5.1 on 2024-09-30 04:11
>>>>>>> ae3964e400743fbbe86e298af8d02484d283913c

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultys',
            name='fid',
        ),
    ]
