# Generated by Django 5.1 on 2024-09-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultys',
            name='fid',
        ),
    ]
