# Generated by Django 5.1 on 2024-10-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='ssubcode',
        ),
        migrations.RemoveField(
            model_name='students',
            name='ssubject',
        ),
    ]
