# Generated by Django 5.1 on 2024-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=255)),
                ('sub_code', models.CharField(max_length=155)),
                ('sub_dept', models.CharField(max_length=255)),
                ('sem', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_subject',
            },
        ),
    ]
